# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: aws-managed-grafana-data-source-loki
  description: This component is responsible for provisioning a Loki data source for an Amazon Managed Grafana workspace
  homepage: https://cloudposse.com/accelerate
  topics: terraform, terraform-component








